import Head from 'next/head'
import { Inter } from '@next/font/google'
import Sidebar from './Components/Sidebar'
import Feed from './Components/Feed'
import Widgets from './Components/Widgets'

const inter = Inter({ subsets: ['latin'] })

export default function Home({newsResults, randomUsersResults}) {
  return (
    <>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto">

        {/* sidebar */}
        <Sidebar/>
        {/* feed */}
        <Feed/>
        
        {/* widgets */}

        <Widgets newsResults={newsResults.articles} randomUsersResults={randomUsersResults.results} />

        {/* model */} 
      </main>

    
    
    </>
  )
}
// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps(){
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res)=> res.json());
  const randomUsersResults = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  ).then((res) => res.json());

  return {
    props: {
      newsResults,
      randomUsersResults,
    },
  };
}

