import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Sidebar from './Components/Sidebar'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen max-w-5xl mx-auto ">

        {/* sidebar */}
        <Sidebar/>
        {/* feed */}

        {/* widgets */}

        {/* model */} 
      </main>

    
    
    </>
  )
}
